# ==========================================
# GOMEZ SYSTEMS - CONFIGURACION DE SERVIDOR
# ==========================================
server.port=8085
spring.thymeleaf.cache=false

# ==========================================
# GOMEZ SYSTEMS - CEREBRO DE DATOS (H2)
# ==========================================
# Base de datos en archivo fisico (Sobrevive a los reinicios)
spring.datasource.url=jdbc:h2:file:./basedatos/gymdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA / Hibernate: Hace la magia de crear las tablas por nosotros
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=false

# Consola Web: Panel secreto para ver las tablas en vivo
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# ==========================================
# GOMEZ SYSTEMS - EVOLUTION API WHATSAPP
# ==========================================
# URL Base de tu API
evolution.url=https://api.gomezz.space
evolution.instance=systems
evolution.apikey=${EVOLUTION_API_KEY:}

# ==========================================
# GOMEZ SYSTEMS - MERCADO PAGO
# ==========================================
mercadopago.access-token=${MERCADOPAGO_TOKEN:}

# ==========================================
# GOMEZ SYSTEMS - SEGURIDAD INTERNA
# ==========================================
app.security.admin.pin=${ADMIN_PIN:1786}
app.security.cajero.pin=${CAJERO_PIN:1234}