# ==========================================
# GOMEZ SYSTEMS - PROD CLOUD ENVIRONMENT
# ==========================================

# En la nube se inyectará $DATABASE_URL o las relativas
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# H2 Console inhabilitada totalmente
spring.h2.console.enabled=false

# Validar Hibernate
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
