# --- BASE DE DATOS Y JPA ---
spring.datasource.url=${DB_URL:jdbc:postgresql://market_db:5432/bot}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASS:Linda236}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# --- SERVIDOR ---
server.port=${PORT:8085}

# --- EVOLUTION API (MOTOR G.O.M.E.Z. WHATSAPP) ---
# Cambia los valores despues de los ':' por los datos reales de tu Evolution API
evolution.api.url=${EVOLUTION_URL:https://api.gomezz.space:8080}
evolution.api.instance=${EVOLUTION_INSTANCE:systems}
evolution.api.token=${EVOLUTION_TOKEN:9FCB1D6E24E9-4815-B408-2EC8C2735312}