# ==========================================
# GOMEZ SYSTEMS - PROD CLOUD ENVIRONMENT
# ==========================================

# 1. Configuracion del Servidor y Red
# Forzar el puerto para que coincida con Easypanel
server.port=8085
# Permitir conexiones externas (Vital para Docker, Easypanel y Wi-Fi)
server.address=0.0.0.0

# 2. Conexion a Base de Datos (PostgreSQL)
# En la nube se inyectaran estos valores desde las variables de entorno
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driverClassName=org.postgresql.Driver

# 3. Configuracion de Hibernate / JPA
# Validar o actualizar la estructura de la base de datos automaticamente
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Seguridad / Otras configuraciones
# H2 Console inhabilitada totalmente por seguridad
spring.h2.console.enabled=false